module.exports = (sequelize, Sequelize) => {
  const Product = sequelize.define("products", {
    name: { type: Sequelize.STRING },
    price: { type: Sequelize.FLOAT },
    description: { type: Sequelize.STRING },
    brand: { type: Sequelize.STRING },
    model: { type: Sequelize.STRING },
    category: { type: Sequelize.STRING },
    serialNumber: { type: Sequelize.STRING },
    batchNo: { type: Sequelize.STRING },
    manufactureDate: { type: Sequelize.DATE },
    warrantyUntil: { type: Sequelize.DATE },
    isUsed: { type: Sequelize.BOOLEAN, defaultValue: false },
    isRefurbished: { type: Sequelize.BOOLEAN, defaultValue: false },
    batteryHealth: { type: Sequelize.INTEGER },
    accessoryStatus: { type: Sequelize.STRING },
    cccNumber: { type: Sequelize.STRING },
    energyLevel: { type: Sequelize.STRING },
    rohsStatus: { type: Sequelize.STRING },
    inspectionAgency: { type: Sequelize.STRING },
    inspectionDate: { type: Sequelize.DATE },
    inspectionConclusion: { type: Sequelize.STRING },
    batterySafetyPassed: { type: Sequelize.BOOLEAN },
    chargerSafetyPassed: { type: Sequelize.BOOLEAN },
    appearanceGrade: { type: Sequelize.STRING },
    functionalTestPassed: { type: Sequelize.BOOLEAN },
    repairHistoryDeclared: { type: Sequelize.BOOLEAN },
    auditReasonCodes: { type: Sequelize.TEXT },
    recallStatus: { type: Sequelize.BOOLEAN, defaultValue: false },
    recallReason: { type: Sequelize.STRING },
    recallNoticeAt: { type: Sequelize.DATE },
    recallBatchNo: { type: Sequelize.STRING },
    ipfsHash: { type: Sequelize.STRING },
    qualificationHash: { type: Sequelize.STRING },
    stock: { type: Sequelize.INTEGER },
    auditStatus: { type: Sequelize.INTEGER },
    txHash: { type: Sequelize.STRING },
    onChainId: { type: Sequelize.INTEGER },
    auditReason: { type: Sequelize.STRING },
    auditBy: { type: Sequelize.INTEGER },
    auditAt: { type: Sequelize.DATE },
    delistReason: { type: Sequelize.STRING },
    delistedBy: { type: Sequelize.INTEGER },
    delistedAt: { type: Sequelize.DATE },
    sellerId: { type: Sequelize.INTEGER },
  });

  return Product;
};
